import type { Metadata } from 'next';
import './globals.css';
import React from 'react';
import { Analytics } from '@vercel/analytics/react';


export const metadata: Metadata = {
    title: 'kutay',
    description: 'Generated by create next app'
};

export default function RootLayout({
                                       children
                                   }: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
        <body className='font-["Space_Grotesk"]'>
        {children}
        <Analytics/>
        </body>
        </html>
    );
}
